theme: minima
title: Rooks Hunter
email: rdh6714@utulsa.edu
description: > # this means to ignore newlines until "baseurl:"

# social links

github_username:  rooksdh

show_excerpts: true # set to false to remove excerpts on the homepage
