theme: minima
title: Sam Shwadlenak Trizza
email: sam-trizza@utulsa.edu
description: > # this means to ignore newlines until "baseurl:"

# social links
facebook_username: sam.trizza
instagram_username: samasiteverwas
linkedin_username: sam-trizza
github_username:  sst972

show_excerpts: true # set to false to remove excerpts on the homepage
