theme: jekyll-theme-slate
title: Rooks Hunter's Tech Resume
author: Rooks Hunter
email: rdh6714@utulsa.edu
description: > # this means to ignore newlines until "baseurl:"
text: Thanks for visiting my technical resume!
location: Tulsa, Oklahoma

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Rooks Hunter"
resume_title:                   "Student"
resume_contact_email:           "rdh6714@utulsa.edu"
resume_contact_telephone:       "214-592-7339"
resume_contact_address:         "Tulsa, Oklahoma"
resume_header_contact_info: "214-592-7339 | rdh6714@utulsa.edu"
resume_header_intro: "<p>We're more than our resumes, but this is a snapshot!</p>"

# social links
facebook_username: sam.trizza
instagram_username: samasiteverwas
linkedin_username: sam-trizza
github_username:  sst972
link: treeringsandsinkingroots.wordpress.com

show_excerpts: true # set to false to remove excerpts on the homepage
